### ISSUE TITLE
No "response_modes_supported" in odic discovery response but mock data holder supports "fragment" only

### ISSUE THREAD

**Issue by Smoovsky** [ConsumerDataRight/mock-data-holder-energy#12]
**Describe the bug**
By standard, it seems when ```"response_modes_supported"``` is omitted, the provider should support both ```["query", "fragment"]``` 

**To Reproduce**
1. pass ```response_mode=query``` in authorization request
2. get bad request result from the mock data holder

**Expected behaviour**
Either oidc discovery response specifies that the provider supports fragment only or the recipient should be able to use query as response mode.

**Comment by CDR-AndrewG** [comment]
Hi @Smoovsky,

Thank you for reaching out and logging this issue. 

The mock-data-holder-energy provides `form_post` and `fragment` as the `repsonse_modes_supported`. The `repsonse_modes_supported` was a recent addition in our latest release. Can you confirm you have the latest code?

The `repsonse_modes_supported` can be seen here - https://dh-energy.idp.cdrsandbox.gov.au/.well-known/openid-configuration for the Energy Data Holder hosted within our [Sandbox](https://cdrsandbox.gov.au/).

The mock-data-holder-energy discovery document is set up here and contains `fragment` and `form_post` - https://github.com/ConsumerDataRight/mock-data-holder-energy/blob/c0e16b483b1cf736d92bd4919a304386b5505830/Source/CDR.DataHolder.IdentityServer/Startup.cs#L442

**Comment by Smoovsky** [comment]
> Hi @Smoovsky,
> 
> Thank you for reaching out and logging this issue.
> 
> The mock-data-holder-energy provides `form_post` and `fragment` as the `repsonse_modes_supported`. The `repsonse_modes_supported` was a recent addition in our latest release. Can you confirm you have the latest code?
> 
> The `repsonse_modes_supported` can be seen here - https://dh-energy.idp.cdrsandbox.gov.au/.well-known/openid-configuration for the Energy Data Holder hosted within our [Sandbox](https://cdrsandbox.gov.au/).
> 
> The mock-data-holder-energy discovery document is set up here and contains `fragment` and `form_post` -
> 
> https://github.com/ConsumerDataRight/mock-data-holder-energy/blob/c0e16b483b1cf736d92bd4919a304386b5505830/Source/CDR.DataHolder.IdentityServer/Startup.cs#L442

Thanks for your reply, looks like I'm currently on an older version of docker image.
By the way, any approximate time range for when the JARM feature will be implemented in the mock data holder? Thanks again.

**Comment by CDR-AndrewG** [comment]
Hi @Smoovsky,

We are looking into updates for FAPI 1.0 Phase 3 now. Aiming for a release in the early new year.
